apiVersion: v1
kind: Service
metadata:
  name: ip-logger
  namespace: web
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector: { app: ip-logger }
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080

